version: 0.2

phases:
  install:
    commands:
      - n 22
      - npm install

  build:
    commands:
      - npm run build api-server
  post_build:
    commands:
      - ls -al

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - './node_modules/**/*'
