version: 0.2

phases:
  install:
    commands:
      - n 22
      - npm install

  build:
    commands:
      - npm run build $APP_NAME
      - npx mikro-orm migration:up --config=./libs/database/mikro-orm.config.ts
  post_build:
    commands:
      - ls -al

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - './node_modules/**/*'
