export enum ErrorCode {
  // 인증/인가
  UNAUTHORIZED = 'A001',
  INVALID_SNS_TOKEN = 'A002',
  FORBIDDEN = 'A003',

  // 유저
  USER_NOT_FOUND = 'U001',
  SNS_USER_INFO_MISMATCH = 'U002',
  NICKNAME_ALREADY_EXISTS = 'U003',

  // 서버 오류
  INTERNAL_SERVER_ERROR = 'G001',
  VALIDATION_ERROR = 'G002',

  // 지역
  REGION_NOT_FOUND = 'R001',

  // 관심도시
  INTEREST_CITY_NOT_FOUND = 'IC001',

  // 관심지역
  INTEREST_REGION_NOT_FOUND = 'IR001',
  INTEREST_REGION_ALREADY_EXISTS = 'IR002',
  INTEREST_REGION_LIMIT_EXCEEDED = 'IR003',
  PRIMARY_INTEREST_REGION_CANNOT_BE_DELETED = 'IR004',
  PRIMARY_INTEREST_REGION_NOT_FOUND = 'IR005',

  // 상품 게시글
  PRODUCT_POST_NOT_FOUND = 'PP001',
  PRODUCT_POST_DELETED = 'PP002',
  PRODUCT_POST_UPDATE_FORBIDDEN = 'PP003',
  PRODUCT_POST_ALREADY_LIKED = 'PP004',
  PRODUCT_POST_ALREADY_HIDDEN = 'PP005',
  PRODUCT_POST_NOT_HIDDEN = 'PP006',
  PRODUCT_POST_RESERVED_CANNOT_HIDE = 'PP007',
  PRODUCT_POST_HIDDEN = 'PP008',
  PRODUCT_POST_NOT_FOR_SALE = 'PP009',

  // 리뷰
  REVIEW_INVALID_RATING = 'RV001',
  REVIEW_SAME_USER = 'RV002',
  REVIEWEE_NOT_FOUND = 'RV003',
  REVIEW_ALREADY_EXISTS = 'RV004',
  REVIEW_NOT_ALLOWED_TRADE_NOT_COMPLETED = 'RV005',

  // 대화방
  CONVERSATION_NOT_FOUND = 'CV001',
  CONVERSATION_SELLER_DELETED = 'CV002',
  CONVERSATION_OWN_POST_NOT_ALLOWED = 'CV003',
  CONVERSATION_PARTICIPANT_ALREADY_LEFT = 'CV004',
  CONVERSATION_ALREADY_MUTED = 'CV005',
  CONVERSATION_ALREADY_UNMUTED = 'CV006',
  CONVERSATION_MESSAGE_BLOCKED = 'CV007',

  // 참가자
  PARTICIPANT_NOT_FOUND = 'PT001',

  // 채팅 고유 기능
  JOIN_ROOM_FAILED = 'CH001',
  LEAVE_ROOM_FAILED = 'CH002',
  SEND_MESSAGE_FAILED = 'CH003',
  MARK_READ_FAILED = 'CH004',

  // 유저 차단
  USER_BLOCK_SELF_NOT_ALLOWED = 'UB001',
  USER_ALREADY_BLOCKED = 'UB002',
  USER_NOT_BLOCKED = 'UB003',
}

export const ErrorMessage = {
  [ErrorCode.CONVERSATION_NOT_FOUND]: 'Conversation not found',
  [ErrorCode.PARTICIPANT_NOT_FOUND]: 'Participant not found in conversation',
  [ErrorCode.JOIN_ROOM_FAILED]: 'Failed to join room',
  [ErrorCode.LEAVE_ROOM_FAILED]: 'Failed to leave room',
  [ErrorCode.SEND_MESSAGE_FAILED]: 'Failed to send message',
  [ErrorCode.MARK_READ_FAILED]: 'Failed to mark messages as read',
} as const;
