export enum ErrorCode {
  // 인증/인가
  UNAUTHORIZED = 'A001',
  INVALID_SNS_TOKEN = 'A002',
  FORBIDDEN = 'A003',

  // 유저
  USER_NOT_FOUND = 'U001',
  SNS_USER_INFO_MISMATCH = 'U002',

  // 서버 오류
  INTERNAL_SERVER_ERROR = 'G001',

  // 지역
  REGION_NOT_FOUND = 'R001',

  // 관심도시
  INTEREST_CITY_NOT_FOUND = 'IC001',

  // 관심지역
  INTEREST_REGION_NOT_FOUND = 'IR001',
  INTEREST_REGION_ALREADY_EXISTS = 'IR002',
  INTEREST_REGION_LIMIT_EXCEEDED = 'IR003',
  PRIMARY_INTEREST_REGION_CANNOT_BE_DELETED = 'IR004',

  // 상품 게시글
  PRODUCT_POST_NOT_FOUND = 'P001',
  PRODUCT_POST_UPDATE_FORBIDDEN = 'P002',
  PRODUCT_POST_DELETED = 'P003',
}
